export interface JakimLocation {
  city: string;
  state: string;
  latitude: number;
  longitude: number;
  zone: string;
  area: string;
}

export const JAKIM_LOCATIONS: JakimLocation[] = [
  { city: "Pulau Aur dan Pulau Pemanggil", state: "Johor", latitude: 1.4927, longitude: 103.7414, zone: "JHR01", area: "Pulau Aur dan Pulau Pemanggil" },
  { city: "Johor Bahru", state: "Johor", latitude: 1.4927, longitude: 103.7414, zone: "JHR02", area: "Johor Bahru, Kota Tinggi, Mersing, Kulai" },
  { city: "Kluang", state: "Johor", latitude: 1.4927, longitude: 103.7414, zone: "JHR03", area: "Kluang, Pontian" },
  { city: "Batu Pahat", state: "Johor", latitude: 1.4927, longitude: 103.7414, zone: "JHR04", area: "Batu Pahat, Muar, Segamat, Gemas Johor, Tangkak" },
  { city: "Kota Setar", state: "Kedah", latitude: 6.1248, longitude: 100.3678, zone: "KDH01", area: "Kota Setar, Kubang Pasu, Pokok Sena (Daerah Kecil)" },
  { city: "Kuala Muda", state: "Kedah", latitude: 6.1248, longitude: 100.3678, zone: "KDH02", area: "Kuala Muda, Yan, Pendang" },
  { city: "Padang Terap", state: "Kedah", latitude: 6.1248, longitude: 100.3678, zone: "KDH03", area: "Padang Terap, Sik" },
  { city: "Baling", state: "Kedah", latitude: 6.1248, longitude: 100.3678, zone: "KDH04", area: "Baling" },
  { city: "Bandar Baharu", state: "Kedah", latitude: 6.1248, longitude: 100.3678, zone: "KDH05", area: "Bandar Baharu, Kulim" },
  { city: "Langkawi", state: "Kedah", latitude: 6.1248, longitude: 100.3678, zone: "KDH06", area: "Langkawi" },
  { city: "Puncak Gunung Jerai", state: "Kedah", latitude: 6.1248, longitude: 100.3678, zone: "KDH07", area: "Puncak Gunung Jerai" },
  { city: "Bachok", state: "Kelantan", latitude: 6.1254, longitude: 102.2383, zone: "KTN01", area: "Bachok, Kota Bharu, Machang, Pasir Mas, Pasir Puteh, Tanah Merah, Tumpat, Kuala Krai, Mukim Chiku" },
  { city: "Gua Musang (Daerah Galas Dan Bertam)", state: "Kelantan", latitude: 6.1254, longitude: 102.2383, zone: "KTN02", area: "Gua Musang (Daerah Galas Dan Bertam), Jeli, Jajahan Kecil Lojing" },
  { city: "SELURUH NEGERI MELAKA", state: "Melaka", latitude: 2.1896, longitude: 102.2501, zone: "MLK01", area: "SELURUH NEGERI MELAKA" },
  { city: "Tampin", state: "Negeri Sembilan", latitude: 2.7259, longitude: 101.9378, zone: "NGS01", area: "Tampin, Jempol" },
  { city: "Jelebu", state: "Negeri Sembilan", latitude: 2.7259, longitude: 101.9378, zone: "NGS02", area: "Jelebu, Kuala Pilah, Rembau" },
  { city: "Port Dickson", state: "Negeri Sembilan", latitude: 2.7259, longitude: 101.9378, zone: "NGS03", area: "Port Dickson, Seremban" },
  { city: "Pulau Tioman", state: "Pahang", latitude: 3.8077, longitude: 103.326, zone: "PHG01", area: "Pulau Tioman" },
  { city: "Kuantan", state: "Pahang", latitude: 3.8077, longitude: 103.326, zone: "PHG02", area: "Kuantan, Pekan, Muadzam Shah" },
  { city: "Jerantut", state: "Pahang", latitude: 3.8077, longitude: 103.326, zone: "PHG03", area: "Jerantut, Temerloh, Maran, Bera, Chenor, Jengka" },
  { city: "Bentong", state: "Pahang", latitude: 3.8077, longitude: 103.326, zone: "PHG04", area: "Bentong, Lipis, Raub" },
  { city: "Genting Sempah", state: "Pahang", latitude: 3.8077, longitude: 103.326, zone: "PHG05", area: "Genting Sempah, Janda Baik, Bukit Tinggi" },
  { city: "Cameron Highlands", state: "Pahang", latitude: 3.8077, longitude: 103.326, zone: "PHG06", area: "Cameron Highlands, Genting Higlands, Bukit Fraser" },
  { city: "Zon Khas Daerah Rompin", state: "Pahang", latitude: 3.8077, longitude: 103.326, zone: "PHG07", area: "Zon Khas Daerah Rompin, (Mukim Rompin, Mukim Endau, Mukim Pontian)" },
  { city: "Kangar", state: "Perlis", latitude: 6.4414, longitude: 100.1983, zone: "PLS01", area: "Kangar, Padang Besar, Arau" },
  { city: "Seluruh Negeri Pulau Pinang", state: "Pulau Pinang", latitude: 5.4141, longitude: 100.3288, zone: "PNG01", area: "Seluruh Negeri Pulau Pinang" },
  { city: "Tapah", state: "Perak", latitude: 4.5975, longitude: 101.0901, zone: "PRK01", area: "Tapah, Slim River, Tanjung Malim" },
  { city: "Kuala Kangsar", state: "Perak", latitude: 4.5975, longitude: 101.0901, zone: "PRK02", area: "Kuala Kangsar, Sg. Siput , Ipoh, Batu Gajah, Kampar" },
  { city: "Lenggong", state: "Perak", latitude: 4.5975, longitude: 101.0901, zone: "PRK03", area: "Lenggong, Pengkalan Hulu, Grik" },
  { city: "Temengor", state: "Perak", latitude: 4.5975, longitude: 101.0901, zone: "PRK04", area: "Temengor, Belum" },
  { city: "Kg Gajah", state: "Perak", latitude: 4.5975, longitude: 101.0901, zone: "PRK05", area: "Kg Gajah, Teluk Intan, Bagan Datuk, Seri Iskandar, Beruas, Parit, Lumut, Sitiawan, Pulau Pangkor" },
  { city: "Selama", state: "Perak", latitude: 4.5975, longitude: 101.0901, zone: "PRK06", area: "Selama, Taiping, Bagan Serai, Parit Buntar" },
  { city: "Bukit Larut", state: "Perak", latitude: 4.5975, longitude: 101.0901, zone: "PRK07", area: "Bukit Larut" },
  { city: "Bahagian Sandakan (Timur)", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH01", area: "Bahagian Sandakan (Timur), Bukit Garam, Semawang, Temanggong, Tambisan, Bandar Sandakan, Sukau" },
  { city: "Beluran", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH02", area: "Beluran, Telupid, Pinangah, Terusan, Kuamut, Bahagian Sandakan (Barat)" },
  { city: "Lahad Datu", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH03", area: "Lahad Datu, Silabukan, Kunak, Sahabat, Semporna, Tungku, Bahagian Tawau  (Timur)" },
  { city: "Bandar Tawau", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH04", area: "Bandar Tawau, Balong, Merotai, Kalabakan, Bahagian Tawau (Barat)" },
  { city: "Kudat", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH05", area: "Kudat, Kota Marudu, Pitas, Pulau Banggi, Bahagian Kudat" },
  { city: "Gunung Kinabalu", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH06", area: "Gunung Kinabalu" },
  { city: "Kota Kinabalu", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH07", area: "Kota Kinabalu, Ranau, Kota Belud, Tuaran, Penampang, Papar, Putatan, Bahagian Pantai Barat" },
  { city: "Pensiangan", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH08", area: "Pensiangan, Keningau, Tambunan, Nabawan, Bahagian Pendalaman (Atas)" },
  { city: "Beaufort", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH09", area: "Beaufort, Kuala Penyu, Sipitang, Tenom, Long Pasia, Membakut, Weston, Bahagian Pendalaman (Bawah)" },
  { city: "Gombak", state: "Selangor", latitude: 3.0738, longitude: 101.5183, zone: "SGR01", area: "Gombak, Petaling, Sepang, Hulu Langat, Hulu Selangor, S.Alam" },
  { city: "Kuala Selangor", state: "Selangor", latitude: 3.0738, longitude: 101.5183, zone: "SGR02", area: "Kuala Selangor, Sabak Bernam" },
  { city: "Klang", state: "Selangor", latitude: 3.0738, longitude: 101.5183, zone: "SGR03", area: "Klang, Kuala Langat" },
  { city: "Limbang", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK01", area: "Limbang, Lawas, Sundar, Trusan" },
  { city: "Miri", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK02", area: "Miri, Niah, Bekenu, Sibuti, Marudi" },
  { city: "Pandan", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK03", area: "Pandan, Belaga, Suai, Tatau, Sebauh, Bintulu" },
  { city: "Sibu", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK04", area: "Sibu, Mukah, Dalat, Song, Igan, Oya, Balingian, Kanowit, Kapit" },
  { city: "Sarikei", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK05", area: "Sarikei, Matu, Julau, Rajang, Daro, Bintangor, Belawai" },
  { city: "Lubok Antu", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK06", area: "Lubok Antu, Sri Aman, Roban, Debak, Kabong, Lingga, Engkelili, Betong, Spaoh, Pusa, Saratok" },
  { city: "Serian", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK07", area: "Serian, Simunjan, Samarahan, Sebuyau, Meludam" },
  { city: "Kuching", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK08", area: "Kuching, Bau, Lundu, Sematan" },
  { city: "Zon Khas (Kampung Patarikan)", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK09", area: "Zon Khas (Kampung Patarikan)" },
  { city: "Kuala Terengganu", state: "Terengganu", latitude: 5.3302, longitude: 103.1408, zone: "TRG01", area: "Kuala Terengganu, Marang, Kuala Nerus" },
  { city: "Besut", state: "Terengganu", latitude: 5.3302, longitude: 103.1408, zone: "TRG02", area: "Besut, Setiu" },
  { city: "Hulu Terengganu", state: "Terengganu", latitude: 5.3302, longitude: 103.1408, zone: "TRG03", area: "Hulu Terengganu" },
  { city: "Dungun", state: "Terengganu", latitude: 5.3302, longitude: 103.1408, zone: "TRG04", area: "Dungun, Kemaman" },
  { city: "Kuala Lumpur", state: "Wilayah Persekutuan", latitude: 3.139, longitude: 101.6869, zone: "WLY01", area: "Kuala Lumpur, Putrajaya" },
  { city: "Labuan", state: "Wilayah Persekutuan", latitude: 5.2831, longitude: 115.2308, zone: "WLY02", area: "Labuan" },
];

export const AUTO_DETECT_LOCATIONS: JakimLocation[] = [
  { city: "Johor Bahru", state: "Johor", latitude: 1.4927, longitude: 103.7414, zone: "JHR02", area: "Johor Bahru, Kota Tinggi, Mersing, Kulai" },
  { city: "Alor Setar", state: "Kedah", latitude: 6.1248, longitude: 100.3678, zone: "KDH01", area: "Kota Setar, Kubang Pasu, Pokok Sena (Daerah Kecil)" },
  { city: "Kota Bharu", state: "Kelantan", latitude: 6.1254, longitude: 102.2383, zone: "KTN01", area: "Bachok, Kota Bharu, Machang, Pasir Mas, Pasir Puteh, Tanah Merah, Tumpat, Kuala Krai, Mukim Chiku" },
  { city: "Melaka", state: "Melaka", latitude: 2.1896, longitude: 102.2501, zone: "MLK01", area: "SELURUH NEGERI MELAKA" },
  { city: "Seremban", state: "Negeri Sembilan", latitude: 2.7259, longitude: 101.9378, zone: "NGS03", area: "Port Dickson, Seremban" },
  { city: "Kuantan", state: "Pahang", latitude: 3.8077, longitude: 103.326, zone: "PHG02", area: "Kuantan, Pekan, Muadzam Shah" },
  { city: "Kangar", state: "Perlis", latitude: 6.4414, longitude: 100.1983, zone: "PLS01", area: "Kangar, Padang Besar, Arau" },
  { city: "George Town", state: "Pulau Pinang", latitude: 5.4141, longitude: 100.3288, zone: "PNG01", area: "Seluruh Negeri Pulau Pinang" },
  { city: "Ipoh", state: "Perak", latitude: 4.5975, longitude: 101.0901, zone: "PRK02", area: "Kuala Kangsar, Sg. Siput , Ipoh, Batu Gajah, Kampar" },
  { city: "Kota Kinabalu", state: "Sabah", latitude: 5.9804, longitude: 116.0735, zone: "SBH07", area: "Kota Kinabalu, Ranau, Kota Belud, Tuaran, Penampang, Papar, Putatan, Bahagian Pantai Barat" },
  { city: "Shah Alam", state: "Selangor", latitude: 3.0738, longitude: 101.5183, zone: "SGR01", area: "Gombak, Petaling, Sepang, Hulu Langat, Hulu Selangor, S.Alam" },
  { city: "Kuching", state: "Sarawak", latitude: 1.5535, longitude: 110.3593, zone: "SWK08", area: "Kuching, Bau, Lundu, Sematan" },
  { city: "Kuala Terengganu", state: "Terengganu", latitude: 5.3302, longitude: 103.1408, zone: "TRG01", area: "Kuala Terengganu, Marang, Kuala Nerus" },
  { city: "Kuala Lumpur", state: "Wilayah Persekutuan", latitude: 3.139, longitude: 101.6869, zone: "WLY01", area: "Kuala Lumpur, Putrajaya" },
  { city: "Labuan", state: "Wilayah Persekutuan", latitude: 5.2831, longitude: 115.2308, zone: "WLY02", area: "Labuan" },
];
